/**
 * This file is partiallty generated. Only make modifications between
 * BEGIN MANUAL SECTION and END MANUAL SECTION designators.
 * 
 * This file is was generated by ./sc scraper script command.
 */
package scraper

import collection.JavaConverters._
import org.jsoup.nodes.Document
import org.jsoup.nodes.Element

import common.CountryType._
import crawler.CrawlerTypes._
/** BEGIN MANUAL SECTION */
/** END MANUAL SECTION */

object WebScraperBusinessInsiderArticle extends TWebScraper {

  def apply(
    page: WebPage,
    linkText: String,
    link: URL,
    html: String,
  ): Option[WebArticle] = {
    val doc = parseHTMLDocument(html).select("main")
    /** BEGIN MANUAL SECTION */
    val section = if (page.url.contains("tecnologia")) {
      "tecnologia"
    } else if (page.url.contains("economia")) {
      "economia"
    } else {
      "tecnologia"
    }
    val baseURL = s"https://${getBaseDomain(page.url)}/$section"

    val title = doc.select("h1.title").text().strip
    val author = doc.select("div.author").text().strip
    val img = doc.select("div.container-img img").attr("src").strip
    val text =
      doc.select("div.article-lead").text().strip + " " + doc.select("div.article-body").text().strip
    val outBoundLinks = doc.select("div.article-body a")
      .asScala
      .map(anchorTag => {
        val href = anchorTag.attr("href").strip()
        val url = if (href.startsWith("http")) {
          href
        } else {
          s"$baseURL$href"
        }
        (anchorTag.text(), url)
      })
      .filter(pair => !pair._1.isEmpty && !pair._2.isEmpty)
      .toSet
    val dateStr = doc.select(".time-flame").text().strip

    val datePublished = scrapeSpanishDate(dateStr)

    val webArticle = WebArticle(
      page,
      linkText,
      link,
      title,
      if (!author.isEmpty) Some(author) else None,
      datePublished,
      outBoundLinks,
      if (!img.isEmpty) Some(img) else None,
      text,
    )
    Some(webArticle)
    /** END MANUAL SECTION */
  }
  /** BEGIN MANUAL METHOD SECTION */
  /** END MANUAL METHOD SECTION */
}

