/**
 * This file is partiallty generated. Only make modifications between
 * BEGIN MANUAL SECTION and END MANUAL SECTION designators.
 * 
 * This file is was generated by ./sc scraper script command.
 */
package scraper

import utest._
import scala.io.Source
import common.CountryType._
import common.CountryType
import common.SourceType._
import common.SourceType
import common.TestUtils
import crawler.CrawlerTypes._
/** BEGIN MANUAL SECTION */
/** END MANUAL SECTION */

object WebScraperBusinessInsiderArticleTests extends TestSuite with TestUtils {
  
  var html = ""

  val BusinessInsiderURL = "https://www.businessinsider.es/tecnologia"
  /** BEGIN MANUAL SECTION */
  /** END MANUAL SECTION */

  override def utestBeforeEach(path: Seq[String]): Unit = {
    if (html.isEmpty) {
      val htmlStream = getClass.getResourceAsStream("/BusinessInsider.html.test")
      html = Source.fromInputStream(htmlStream).getLines.mkString
    }
  }

  def tests = Tests {
    test("Web Scrape BusinessInsider") {
      /** END BEGIN SECTION */
      val page = WebPage(BusinessInsiderURL, CountryType.ESPANA, SourceType.BUSINESS_INSIDER)
      val linkURL = "https://www.businessinsider.es/autentica-navaja-suiza-tecnologia-router-disco-duro-bateria-externa-servidor-solo-40-euros-688759"
      val linkText = "La auténtica navaja suiza de la tecnología: router, disco duro, batería externa y servidor por sólo 40 euros"
      val author = "Sandra Arteaga"
      val maybeArticle: Option[WebArticle] = WebScraperBusinessInsiderArticle(
        page,
        linkText,
        linkURL,
        html,
      )
      val thumb = "https://cdn.businessinsider.es/sites/navi.axelspringer.es/public/styles/480/public/media/image/2019/09/ravpower-filehub.jpg?itok=KWJT_Jnl"
      val date = ArticleDate(1,8,2020)
      maybeArticle match {
        case Some(a: WebArticle) => testArticle(
          a,
          page,
          linkText,
          linkURL,
          thumb,
          date,
          Some(author),
        )
        case _ => assert(false)
      }
      /** END MANUAL SECTION */
    }
  }
  /** BEGIN MANUAL SECTION */
  private def testArticle(
    a: WebArticle,
    origin: WebPage,
    linkText: String,
    linkURL: URL,
    thumb: URL,
    date: ArticleDate,
    author: Option[String],
  ): Unit = {
    assert(a.title == "La auténtica navaja suiza de la tecnología: router, disco duro, batería externa y servidor por sólo 40 euros")
    assert(a.origin == origin)
    assert(a.originLinkText == linkText)
    assert(a.fullyQualifiedLink == linkURL)
    assert(checkOptionalMatch(a.image, thumb))
    assert(checkOptionalMatch(a.datePublished, date))
    assert(a.outBoundLinks.size > 0)
    assert(!a.text.contains("<html>"))
    assert(!a.text.contains("<body>"))
    assert(!a.text.contains("<script>"))
    assert(checkOptionalMatch(a.author, "Sandra Arteaga"))
    a.outBoundLinks.foreach(linkPair => {
      val (text, url) = linkPair
      assert(!text.isEmpty)
      assert(url.startsWith("http"))
    })
  }
  /** END MANUAL SECTION */
}

