/**
 * This file is partiallty generated. Only make modifications between
 * BEGIN MANUAL SECTION and END MANUAL SECTION designators.
 * 
 * This file is was generated by ./sc scraper script command.
 */
package scraper

import utest._
import scala.io.Source
import common.CountryType._
import common.CountryType
import common.SourceType._
import common.SourceType
import common.TestUtils
import crawler.CrawlerTypes._
/** BEGIN MANUAL SECTION */
/** END MANUAL SECTION */

object WebScraperCNNArticleTests extends TestSuite with TestUtils {
  
  var html = ""

  val CNNURL = "https://cnnespanol.cnn.com/seccion/tecnologia/"
  /** BEGIN MANUAL SECTION */
  /** END MANUAL SECTION */

  override def utestBeforeEach(path: Seq[String]): Unit = {
    if (html.isEmpty) {
      val htmlStream = getClass.getResourceAsStream("/CNN.html.test")
      html = Source.fromInputStream(htmlStream).getLines.mkString
    }
  }

  def tests = Tests {
    test("Web Scrape CNN") {
      val page = WebPage(CNNURL, CountryType.EEUU, SourceType.CNN)
      val linkURL = "https://cnnespanol.cnn.com/video/agujeros-azules-blue-holes-misterio-oceano-mar-profundidad-henry-briceno-profesor-instituto-del-ambiente-universidad-internacional-florida-guillermo-arduino-encuentro-cnne/"
      val linkText = "Ehécatl 4T y Gätsi, ventiladores mexicanos contra el covid-19"
      val author = "Mario González"
      val maybeArticle: Option[WebArticle] = WebScraperCNNArticle(
        page,
        linkText,
        linkURL,
        html,
      )
      val thumb = ""
      val date = ArticleDate(14,7,2020)
      maybeArticle match {
        case Some(a: WebArticle) => testArticle(
          a,
          page,
          linkText,
          linkURL,
          thumb,
          date,
          author,
        )
        case _ => assert(false)
      }
      /** END MANUAL SECTION */
    }
  }
  /** BEGIN MANUAL SECTION */
  private def testArticle(
    a: WebArticle,
    origin: WebPage,
    linkText: String,
    linkURL: URL,
    thumb: URL,
    date: ArticleDate,
    author: String,
  ): Unit = {
    assert(a.title == "México anuncia fabricación en serie de ventiladores hechos con tecnología 100% mexicana y a menor costo")
    assert(a.origin == origin)
    assert(a.originLinkText == linkText)
    assert(a.fullyQualifiedLink == linkURL)
    assert(!checkOptionalMatch(a.image, thumb))
    assert(checkOptionalMatch(a.datePublished, date))
    assert(a.outBoundLinks.size > 0)
    assert(!a.text.contains("<html>"))
    assert(!a.text.contains("<body>"))
    assert(!a.text.contains("<script>"))
    assert(checkOptionalMatch(a.author, author))
    a.outBoundLinks.foreach(linkPair => {
      val (text, url) = linkPair
      assert(!text.isEmpty)
      assert(url.startsWith("http"))
    })
  }
  /** END MANUAL SECTION */
}

