/**
  * This file code-gens scrapers for rapid development
  * Usage ./scraper <SCRAPER_NAME>
  */
object ScraperTestScraper {

  def main(args: Array[String]): Unit = {
    val scraperName = args(0)
    val scraperTest =
s"""/**
 * This file is partiallty generated. Only make modifications between
 * BEGIN MANUAL SECTION and END MANUAL SECTION designators.
 * 
 * This file is was generated by ./sc scraper script command.
 */
package scraper

import utest._
import scala.io.Source
import common.CountryType._
import common.CountryType
import common.SourceType._
import common.SourceType
import common.TestUtils
import crawler.CrawlerTypes._
/** BEGIN MANUAL SECTION */
/** END MANUAL SECTION */

object WebScraper${scraperName}ArticleTests extends TestSuite with TestUtils {
  
  var html = ""

  val ${scraperName}URL = /** Replace with URL */
  /** BEGIN MANUAL SECTION */
  /** END MANUAL SECTION */

  override def utestBeforeEach(path: Seq[String]): Unit = {
    if (html.isEmpty) {
      val htmlStream = getClass.getResourceAsStream("/${scraperName}.html")
      html = Source.fromInputStream(htmlStream).getLines.mkString
    }
  }

  def tests = Tests {
    test("Web Scrape ${scraperName}") {
      /** END BEGIN SECTION */
      val page = WebPage(/** Replace with args */)
      val linkURL = "/* Replace me */"
      val linkText = "/* Replace me */"
      val author = "/* Replace me */"
      val maybeArticle: Option[WebArticle] = WebScraper${scraperName}Article(
        page,
        linkText,
        linkURL,
        html,
      )
      val thumb = "/* Replace me */"
      val date = ArticleDate(/** Replace with args */)
      maybeArticle match {
        case Some(a: WebArticle) => testArticle(
          a,
          page,
          linkText,
          linkURL,
          thumb,
          date,
          author,
        )
        case _ => assert(false)
      }
      /** END MANUAL SECTION */
    }
  }
  /** BEGIN MANUAL SECTION */
  private def testArticle(
    a: WebArticle,
    origin: WebPage,
    linkText: String,
    linkURL: URL,
    thumb: URL,
    date: ArticleDate,
    author: Option[String],
  ): Unit = {
    assert(a.title == "")
    assert(a.origin == origin)
    assert(a.originLinkText == linkText)
    assert(a.fullyQualifiedLink == linkURL)
    assert(checkOptionalMatch(a.image, thumb))
    assert(checkOptionalMatch(a.datePublished, date))
    assert(a.outBoundLinks.size > 0)
    assert(!a.text.contains("<html>"))
    assert(!a.text.contains("<body>"))
    assert(!a.text.contains("<script>"))
    assert(!checkOptionalMatch(a.author, ""))
    a.outBoundLinks.foreach(linkPair => {
      val (text, url) = linkPair
      assert(!text.isEmpty)
      assert(url.startsWith("http"))
    })
  }
  /** END MANUAL SECTION */
}
"""
    // Send to STDOUT
    println(scraperTest)
  }
}