/**
  * This file code-gens scrapers for rapid development
  * Usage ./scraper <SCRAPER_NAME>
  */
object ScraperHTMLScript {

  def main(args: Array[String]): Unit = {
    val scraperName = args(0)
    val html =
s"""<!--
 This file is partiallty generated. Only make modifications between
 BEGIN MANUAL SECTION and END MANUAL SECTION designators.

 This file is was generated by ./sc scraper script command.
-->
<html>
  <body>
  <!-- BEGIN MANUAL SECTION -->
  <!-- END MANUAL SECTION -->
  </body>
</html>
"""
    // Send to STDOUT
    println(html)
  }
}